# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -direct" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded ext_prog 1.0 [list source [file join $dir ext_prog.tcl]]
package ifneeded lcp 1.0 [list source [file join $dir lcp.tcl]]
package ifneeded logchem_ui 1.0 [list source [file join $dir logchem_ui.tcl]]
